<template>
  <v-footer
    height="auto"
  >
    <v-layout
      justify-center
      row
      wrap
    >
      <v-flex
        py-3
        text-xs-center
        black--text
        xs12
      >
        &copy;{{ new Date().getFullYear() }} — <strong>杰旭教育MBA</strong>
      </v-flex>
    </v-layout>
  </v-footer>
</template>
