import Vue from 'vue';
import ChevronRight from 'vue-material-design-icons/ChevronRight.vue';
import MapMarker from 'vue-material-design-icons/MapMarker.vue';
import ContactPhone from 'vue-material-design-icons/ContactPhone.vue';
import ViewHeadline from 'vue-material-design-icons/ViewHeadline.vue';
import AccountQuestion from 'vue-material-design-icons/AccountQuestionOutline';
import SinaWeibo from 'vue-material-design-icons/SinaWeibo';
import WeChat from  'vue-material-design-icons/Wechat';
import Apple from  'vue-material-design-icons/Apple';
Vue.component('chervon-right', ChevronRight);
Vue.component('map-marker', MapMarker);
Vue.component('contact-phone', ContactPhone);
Vue.component('view-headline', ViewHeadline);
Vue.component('account-question', AccountQuestion);
Vue.component('sina-weibo', SinaWeibo);
Vue.component('we-chat', WeChat);
Vue.component('apple', Apple);
